"""learning language rev

Revision ID: 0302e0c70f57
Revises: 301faba70805
Create Date: 2026-09-03 00:57:08.516800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0302e0c70f57'
down_revision: Union[str, Sequence[str], None] = '301faba70805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('learning_language', sa.String(length=100), nullable=False, server_default='English'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'learning_language')
    # ### end Alembic commands ###
