"""add parent deck relationship

Revision ID: 3169a202cc71
Revises: f75920f7e98e
Create Date: 2026-08-24 15:52:23.340622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3169a202cc71'
down_revision: Union[str, Sequence[str], None] = 'f75920f7e98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('parent_deck_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'decks', 'decks', ['parent_deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'parent_deck_id')
    # ### end Alembic commands ###
