"""add generation status to decks

Revision ID: 70d8b654a4fa
Revises: 3169a202cc71
Create Date: 2026-08-30 00:35:58.527004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d8b654a4fa'
down_revision: Union[str, Sequence[str], None] = '3169a202cc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('generation_status', sa.String(length=20), nullable=False, server_default="completed",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'generation_status')
    # ### end Alembic commands ###
