"""add deck position

Revision ID: cf33830d223e
Revises: 0302e0c70f57
Create Date: 2026-09-04 00:43:18.509375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf33830d223e'
down_revision: Union[str, Sequence[str], None] = '0302e0c70f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('position', sa.Integer(), nullable=False, server_default="0",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'position')
    # ### end Alembic commands ###
